- name: Create admintools folder
  file:
    path: /opt/admintools
    state: directory
    owner: '{{ wordpress_user }}'
    group: '{{ wordpress_user }}'
    mode: '755'

- name: Copy restore scripts files
  copy:
    src: "{{ item }}"
    dest: "/opt/admintools/"
    owner: '{{ wordpress_user }}'
    group: '{{ wordpress_user }}'
  with_items:
  - create-key.py
  - encrypt.py
  - restore-wp.py
  - backup-wp.py
  - tools.py
  - requirements.txt

- name: Copy configuration files
  copy:
    src: "{{ item }}"
    dest: "/etc/"
    owner: '{{ wordpress_user }}'
    group: '{{ wordpress_user }}'
  with_items:
  - AES.key
  - backup-wp.conf

- name: install setuptools
  apt:
    name: python3-setuptools
    state: present

- name: install pip
  apt:
    name: python3-pip
    state: present

- name: Install Python requirements
  pip:
    requirements: "/opt/admintools/requirements.txt"

- name: First ensure that backup dir exist
  file:
    path: "{{ backup_dir }}"
    state: directory
    owner: '{{ wordpress_user }}'
    group: '{{ wordpress_user }}'
    mode: '775'

- name: Restore from last backup
  become: yes
  become_user: '{{ wordpress_user }}'
  remote_tmp: '/tmp'
  shell:
    cmd: "python3 /opt/admintools/restore-wp.py"
    chdir: "/opt/admintools"
  notify:
  - restart apache

- name: Create crontab for backup
  cron:
    minute: "21"
    hour: "3"
    user: '{{ wordpress_user }}'
    job: "python3 /opt/admintools/backup-wp.py"